"""create employees table

Revision ID: 096106590be8
Revises:
Create Date: 2026-07-03 20:25:28.927213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "096106590be8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=False),
        sa.Column("phone", sa.String(length=15), nullable=True),
        sa.Column("photo_filename", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
    )
    op.create_index(
        op.f("ix_employees_birth_date"), "employees", ["birth_date"], unique=False
    )
    op.create_index(
        op.f("ix_employees_first_name"), "employees", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_employees_last_name"), "employees", ["last_name"], unique=False
    )
    op.create_index(op.f("ix_employees_phone"), "employees", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employees_phone"), table_name="employees")
    op.drop_index(op.f("ix_employees_last_name"), table_name="employees")
    op.drop_index(op.f("ix_employees_first_name"), table_name="employees")
    op.drop_index(op.f("ix_employees_birth_date"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
